version: '3'
services:
  pythonapp:
    build: ./python
    command: /bin/sh -c 'service cron start;cron -f;chmod +x /app/start.sh; /app/start.sh'
    ports:
      - '5000:5000'
    volumes:
       - ./python:/app
    privileged: true
    environment:
      USER: 'root'
      PASSWORD: 'root'
      HOST: 'mysql'
      PORT: '3306'
      DATABASE: 'db'
    depends_on:
      - mysql

  mysql:
    build:
      context: ./mysql/
    restart: always
    volumes:
      - ./mysql:/app
        # - mysqldata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'root'
    ports:
      - '3333:3306'

#volumes:
  # mysqldata:
